AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer for Web system

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
          #ALBもしくはNLBを表すリソースタイプ
    Properties:
      Name: WebALB
      Scheme: internet-facing #ALBのアクセス可能範囲/Public・Privateか
      Subnets:
        - !ImportValue PublicSubnetA
        - !ImportValue PublicSubnetC
      SecurityGroups:
        - !ImportValue ALBSecurityGroupID
      Type: application #ここでALBに指定
      IpAddressType: ipv4 #dualstack(IPv4/6両方使用)も選べる
      Tags:
        - Key: Name
          Value: WebALB

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: WebTargetGroup
      Port: 80
      Protocol: HTTP #HTTPS(Port:443)も指定可能,その場合証明書が必要
      TargetType: instance #またはIP,Lambda
      VpcId: !ImportValue WebSystemVPCID
      HealthCheckProtocol: HTTP
      HealthCheckPath: / 
      #ALBは定期的にこの指定されたパス（例：http://ターゲットIP/）にアクセスし、レスポンスコードが 200 などの成功ステータスかどうかを判定します。
      Matcher:
        HttpCode: 200-399
#ターゲットから返される HTTPレスポンスコードが下記で指定するHttpCode の範囲内ならHealthyとみなすというルールです。
      Tags:
        - Key: Name
          Value: WebTargetGroup
#ALBが受けたリクエストを「どのプロトコルで」「どのポートで」受け付けるか「どこへ転送するか」を設定する
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB #ALBの一意識別子（ARN）
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward #リクエストをターゲットグループへ「転送する」アクション
          TargetGroupArn: !Ref ALBTargetGroup
Outputs:
  ALBTargetGroupARN:
    Description: ARN of the ALB Target Group
    Value: !Ref ALBTargetGroup
    Export:
      Name: ALBTargetGroupARN
