AWSTemplateFormatVersion: "2010-09-09"
Description: EC2インスタンス（Session Manager専用）を2AZに展開

Resources:
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: /
      RoleName: EC2SessionManagerRole

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole
      InstanceProfileName: EC2SessionManagerProfile

  WebServerInstanceA:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}"
      SubnetId: !ImportValue PrivateSubnetA
      SecurityGroupIds:
        - !ImportValue EC2SecurityGroupID
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf update -y
          dnf install -y httpd mariadb105
          systemctl start httpd
          systemctl enable httpd
          echo "Hello from $(hostname)" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: WebServerInstanceA

  WebServerInstanceC:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}"
      SubnetId: !ImportValue PrivateSubnetC
      SecurityGroupIds:
        - !ImportValue EC2SecurityGroupID
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf update -y
          dnf install -y httpd mariadb105
          systemctl start httpd
          systemctl enable httpd
          echo "Hello from $(hostname)" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: WebServerInstanceC
